[package]
name = "bounce_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy-inspector-egui = { workspace = true }
rand = "0.9.2"
core_engine = { path = "../../crates/core_engine" }
