[package]
name = "tiny_tycoon"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
core_engine = { path = "../../crates/core_engine" }
