[workspace]
members = ['crates/*', "games/*"]
resolver = "2"

[workspace.dependencies]
bevy = "0.17.2"
bevy-inspector-egui = "0.35.0"
bevy_common_assets = { version = "0.14", features = ["ron"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.11.0"
