[package]
name = "bevy_lab"
version = "0.1.0"
edition = "2024"

[workspace]
members = ['crates/*', "games/*"]
resolver = "2"

[workspace.dependencies]
bevy = "0.17.2"
serde = { version = "1.0", features = ["derive"] }
ron = "0.11.0"

[dependencies]
