[package]
name = "square_chaser"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy-inspector-egui = { workspace = true }
bevy_common_assets = { workspace = true }
serde = { workspace = true }
rand = "0.9.2"
core_engine = { path = "../../crates/core_engine" }
