[package]
name = "square_chaser"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
core_engine = { path = "../../crates/core_engine" }
ui_common = { path = "../../crates/ui_common" }
